export const HEADREGISTERSUCCESS = "HEADREGISTERSUCCESS";

export const MEMBERREGISTERSUCCESS = "MEMBERREGISTERSUCCESS";

export const HEADLOGINLOADING = "HEADLOGINLOADING";
export const HEADLOGINSUCCESS = "HEADLOGINSUCCESS";
export const HEADLOGINERROR = "HEADLOGINERROR";

export const MEMBERLOGINLOADING = "MEMBERLOGINLOADING";
export const MEMBERLOGINSUCCESS = "MEMBERLOGINSUCCESS";
export const MEMBERLOGINERROR = "MEMBERLOGINERROR";
